Import('env')

objects = list(map(env.ObjectGenHeader, [
    'OBJLoader.h',
    'STBLoader.h',
    'TextureLoader.h',
]))

objects += list(map(env.Object, [
    'GLTFImporter.cpp',
    'OBJLoader.cpp',
    'STBLoader.cpp',
    'TextureLoader.cpp',
]))

Return('objects')
