Import('env')

objects = map(env.ObjectGenHeader, [
    'OBJLoader.h',
    'STBLoader.h',
    'TextureLoader.h',
])

objects += map(env.Object, [
    'OBJLoader.cpp',
    'STBLoader.cpp',
    'TextureLoader.cpp',
])

Return('objects')
