import os

Import('manager')

depends = [
    'External/SDL',
    '3rdParty/glm',
]

env = manager.CreateEnvironment(depends = depends)
Export('env')

objects = map(env.Object, [
    'Source/Log.cpp',
    'Source/Path.cpp',
    'Source/PixelFormat.cpp',
    'Source/String.cpp',
])

manager.AddComponent(
    name = 'Engine/Core',
    depends = depends,
    objects = objects)
