import os

Import('manager')

depends = [
    'External/SDL',
    '3rdParty/glm',
    '3rdParty/xxHash',
]

env = manager.CreateEnvironment(depends = depends)
Export('env')

objects = map(env.Object, [
    'Math/BoundingBox.cpp',
    'Math/Frustum.cpp',
    'Math/Intersect.cpp',
    'Math/Sphere.cpp',

    'Base64.cpp',
    'DataStream.cpp',
    'LinearAllocator.cpp',
    'Log.cpp',
    'Path.cpp',
    'PixelFormat.cpp',
    'RefCounted.cpp',
    'String.cpp',
    'Thread.cpp',
])

manager.AddComponent(
    name = 'Engine/Core',
    depends = depends,
    objects = objects)

if env['PLATFORM'] in ['Linux']:
    dir = 'POSIX'
else:
    dir = env['PLATFORM']

objects += SConscript(dirs = [dir])
