import os

Import('manager')

depends = [
    'External/SDL',
    '3rdParty/glm',
    '3rdParty/xxHash',
]

env = manager.CreateEnvironment(depends = depends)
Export('env')

objects = map(env.Object, [
    'Source/DataStream.cpp',
    'Source/Log.cpp',
    'Source/Path.cpp',
    'Source/PixelFormat.cpp',
    'Source/RefCounted.cpp',
    'Source/String.cpp',
])

manager.AddComponent(
    name = 'Engine/Core',
    depends = depends,
    objects = objects)

if env['PLATFORM'] in ['Linux']:
    dir = os.path.join('Source', 'POSIX')
else:
    dir = os.path.join('Source', env['PLATFORM'])

objects += SConscript(dirs = [dir])
