import VCS

Import('env')

objects = list(map(env.ObjectGenHeader, [
    'Behaviour.h',
    'Component.h',
    'Entity.h',
    'World.h',
]))

objects += list(map(env.Object, [
    'Behaviour.cpp',
    'Component.cpp',
    'Entity.cpp',
    'World.cpp',
    'WorldEditorWindow.cpp',
]))

Return('objects')
