Import('manager')

env = manager.CreateEnvironment(depends = ['Engine'])

objects = list(map(env.ObjectGenHeader, [
    'Source/PlayerController.h',
    'Source/TestGame.h',
]))

objects += list(map(env.Object, [
    'Source/PlayerController.cpp',
    'Source/TestGame.cpp',
]))

target = env.GeminiGame(name = 'Test', sources = objects)
Return('target')
