Import('manager')

env = manager.CreateEnvironment(depends = ['Engine'])

objects = map(env.ObjectGenHeader, [
    'Source/TestGame.h',
])

objects += map(env.Object, [
    'Source/TestGame.cpp',
])

target = env.OrionGame(name = 'Test', sources = objects)
Return('target')
