Import('env')

objects = map(env.ObjectGenHeader, [
    'BasicRenderPipeline.h',
    'Camera.h',
    'DeferredRenderPipeline.h',
    'EntityRenderer.h',
    'Light.h',
    'Material.h',
    'MeshRenderer.h',
    'RenderDefs.h',
    'RenderPipeline.h',
    'ShaderParameter.h',
    'ShaderTechnique.h',
])

objects += map(env.Object, [
    'BasicRenderPipeline.cpp',
    'Camera.cpp',
    'DeferredRenderPipeline.cpp',
    'EntityDrawList.cpp',
    'EntityRenderer.cpp',
    'Light.cpp',
    'Material.cpp',
    'MeshRenderer.cpp',
    'RenderDefs.cpp',
    'RenderEntity.cpp',
    'RenderContext.cpp',
    'RenderGraph.cpp',
    'RenderLayer.cpp',
    'RenderLight.cpp',
    'RenderManager.cpp',
    'RenderOutput.cpp',
    'RenderPipeline.cpp',
    'RenderView.cpp',
    'RenderWorld.cpp',
    'ShaderCompiler.cpp',
    'ShaderManager.cpp',
    'ShaderParameter.cpp',
    'ShaderTechnique.cpp',
    'TonemapPass.cpp',
])

Return('objects')
