Import('manager')

env = manager.CreateEnvironment(depends = ['Engine/Base'])

objects = list(map(env.ObjectGenHeader, [
    'Source/MTRenderTestGame.h',
]))

objects += list(map(env.Object, [
    'Source/MTRenderTestGame.cpp',
]))

target = env.GeminiGame(name = 'MTRenderTest', sources = objects)
Return('target')
