import os

Import('env')

objects = map(env.Object, [
    'GPUArgumentSet.cpp',
    'GPUBuffer.cpp',
    'GPUCommandList.cpp',
    'GPUDevice.cpp',
    'GPUPipeline.cpp',
    'GPURenderPass.cpp',
    'GPUResource.cpp',
    'GPUResourceView.cpp',
    'GPUShader.cpp',
    'GPUState.cpp',
    'GPUSwapchain.cpp',
    'GPUTexture.cpp',

    'Vulkan/VulkanArgumentSet.cpp',
    'Vulkan/VulkanBuffer.cpp',
    'Vulkan/VulkanCommandList.cpp',
    'Vulkan/VulkanCommandPool.cpp',
    'Vulkan/VulkanContext.cpp',
    'Vulkan/VulkanDescriptorPool.cpp',
    'Vulkan/VulkanInstance.cpp',
    'Vulkan/VulkanDefs.cpp',
    'Vulkan/VulkanDevice.cpp',
    'Vulkan/VulkanFormat.cpp',
    'Vulkan/VulkanMemoryManager.cpp',
    'Vulkan/VulkanPipeline.cpp',
    'Vulkan/VulkanResourceView.cpp',
    'Vulkan/VulkanShader.cpp',
    'Vulkan/VulkanSwapchain.cpp',
    'Vulkan/VulkanTexture.cpp',
    'Vulkan/VulkanUniformPool.cpp',

    'Vulkan/${PLATFORM}/${PLATFORM}VulkanInstance.cpp',
    'Vulkan/${PLATFORM}/${PLATFORM}VulkanSwapchain.cpp',
])

Return('objects')
