import VCS

Import('env')

objects = map(env.ObjectGenHeader, [
    'Game.h',
    'Object.h',
])

objects += map(env.Object, [
    'Engine.cpp',
    'ImGUI.cpp',
    'JSONSerialiser.cpp',
    'Main.cpp',
    'Object.cpp',
    'Serialiser.cpp',
    'Version.cpp',
    'Window.cpp',
])

# Generate the version information file.
def GenerateVersionCPP(target, source, env):
    version = VCS.RevisionID()

    f = open(str(target[0]), 'w')
    f.write('const char *gVersionString = "%s";\n' % (version))
    f.close()
AlwaysBuild(env.Command('Version.cpp', [], env.Action(GenerateVersionCPP, None)))

Return('objects')
