import os

Import('manager')

# Bullet.
manager.AddComponent(
    name = 'External/Bullet',
    includePath = Dir('../Common/Bullet/Include'),
    libPath = Dir('Bullet/Lib'),
    libs = ['BulletSoftBody', 'BulletDynamics', 'BulletCollision', 'LinearMath'])

# libclang.
manager.AddComponent(
    name = 'External/libclang',
    includePath = Dir('libclang/Include'),
    libPath = Dir('libclang/Lib'),
    libs = ['libclang'],
    dlls = File('libclang/Lib/libclang.dll'))

# SDL.
manager.AddComponent(
    name = 'External/SDL',
    includePath = Dir('SDL/Include'),
    libPath = Dir('SDL/Lib'),
    libs = ['SDL2', 'SDL2main'],
    dlls = File('SDL/Lib/SDL2.dll'))

# shaderc.
manager.AddComponent(
    name = 'External/shaderc',
    includePath = Dir('../Common/shaderc/Include'),
    libPath = Dir('shaderc/Lib'),
    libs = ['shaderc_combined'])

# Vulkan SDK.
#
# Just need headers, we load dynamically at runtime.
manager.AddComponent(
    name = 'External/Vulkan',
    includePath = manager.baseEnv['ENV']['VULKAN_SDK'] + '/Include')
